"""Domain schema — the three-layer article and story model (§4.2, §6).

Revision ID: 0002_domain_schema
Revises: 0001_create_heartbeats

Creates the canonical data model: sources and tags, articles and stories, versioned AI
results, feed instances, and the operational tables (jobs, logs, audit, change history,
notifications).

Two database-level guarantees are installed at the end of `upgrade()`, because the rules
they enforce are too important to leave to application discipline:

  1. `articles_original_data_is_immutable` — rejects any UPDATE that changes an
     `original_*` column. That is Non-Negotiable #1 ("original source data is never
     overwritten by AI or system-derived content") enforced by Postgres itself. An ORM
     mistake, a stray script, or a future contributor cannot violate it.

  2. `set_updated_at` — maintains `updated_at` on every domain table using
     `clock_timestamp()`, so a row cannot be modified without the timestamp moving. The
     audit trail (§36, §37) depends on that. `clock_timestamp()` rather than `now()`
     because `now()` is fixed for the whole transaction, which would leave two changes
     in one transaction indistinguishable.

Both are reversible: `downgrade()` drops the triggers and functions before the tables.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002_domain_schema'
down_revision: Union[str, None] = '0001_create_heartbeats'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

#: Every table carrying `updated_at`; each gets the maintenance trigger below.
TIMESTAMPED_TABLES = (
    "ai_results",
    "articles",
    "feed_instances",
    "notifications",
    "processing_jobs",
    "reader_preferences",
    "review_queue_items",
    "saved_views",
    "settings",
    "source_types",
    "sources",
    "stories",
    "story_claim_values",
    "story_claims",
    "story_timeline_events",
    "tags",
    "users",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_articles', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.String(length=20), nullable=False),
    sa.Column('min_importance_score', sa.Float(), nullable=True),
    sa.Column('min_trending_score', sa.Float(), nullable=True),
    sa.Column('max_articles_per_source_per_hour', sa.Integer(), nullable=True),
    sa.Column('ai_headlines_enabled', sa.Boolean(), nullable=False),
    sa.Column('ai_summaries_enabled', sa.Boolean(), nullable=False),
    sa.Column('clustering_enabled', sa.Boolean(), nullable=False),
    sa.Column('synthesis_enabled', sa.Boolean(), nullable=False),
    sa.Column('trending_enabled', sa.Boolean(), nullable=False),
    sa.Column('summary_length', sa.String(length=20), nullable=False),
    sa.Column('headline_style', sa.String(length=60), nullable=True),
    sa.Column('rss_enabled', sa.Boolean(), nullable=False),
    sa.Column('rss_cached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('story_count', sa.Integer(), nullable=False),
    sa.Column('stories_last_24h', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_built_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sort_order IN ('newest', 'trending', 'importance', 'most_sources')", name=op.f('ck_feed_instances_feed_sort_known')),
    sa.CheckConstraint("summary_length IN ('short', 'standard', 'detailed')", name=op.f('ck_feed_instances_feed_summary_length_known')),
    sa.CheckConstraint('max_articles > 0', name=op.f('ck_feed_instances_feed_max_articles_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feed_instances')),
    sa.UniqueConstraint('slug', name=op.f('uq_feed_instances_slug'))
    )
    op.create_table('reader_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reader_key', sa.String(length=120), nullable=False),
    sa.Column('preference', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reader_preferences')),
    sa.UniqueConstraint('reader_key', 'preference', 'value', name='reader_pref_once')
    )
    op.create_table('source_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_types')),
    sa.UniqueConstraint('slug', name=op.f('uq_source_types_slug'))
    )
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('state_is_manual', sa.Boolean(), nullable=False),
    sa.Column('first_reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('trending_score', sa.Float(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('has_manual_override', sa.Boolean(), nullable=False),
    sa.Column('has_unresolved_conflicts', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('emerging', 'developing', 'active', 'stable', 'cooling', 'archived')", name=op.f('ck_stories_story_state_known')),
    sa.CheckConstraint('source_count >= 0', name=op.f('ck_stories_source_count_non_negative')),
    sa.CheckConstraint('trending_score IS NULL OR (trending_score >= 0 AND trending_score <= 100)', name=op.f('ck_stories_trending_in_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stories')),
    sa.UniqueConstraint('slug', name=op.f('uq_stories_slug'))
    )
    op.create_index('ix_stories_state', 'stories', ['state', 'last_updated_at'], unique=False)
    op.create_index('ix_stories_trending', 'stories', ['trending_score', 'last_updated_at'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('component', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_logs'))
    )
    op.create_index(op.f('ix_system_logs_logged_at'), 'system_logs', ['logged_at'], unique=False)
    op.create_index('ix_system_logs_recent', 'system_logs', ['logged_at', 'level'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_ai_suggested', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id <> parent_id', name=op.f('ck_tags_tag_not_its_own_parent')),
    sa.ForeignKeyConstraint(['parent_id'], ['tags.id'], name=op.f('fk_tags_parent_id_tags'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('slug', name=op.f('uq_tags_slug'))
    )
    op.create_index(op.f('ix_tags_parent_id'), 'tags', ['parent_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'administrator', 'editor', 'reviewer', 'read_only')", name=op.f('ck_users_user_role_known')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('change_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=80), nullable=False),
    sa.Column('previous_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_undoable', sa.Boolean(), nullable=False),
    sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('undone_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['undone_by_user_id'], ['users.id'], name=op.f('fk_change_history_undone_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_change_history_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_history'))
    )
    op.create_index('ix_change_history_entity', 'change_history', ['entity_type', 'entity_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_change_history_occurred_at'), 'change_history', ['occurred_at'], unique=False)
    op.create_table('feed_instance_entries',
    sa.Column('feed_instance_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rank_score', sa.Float(), nullable=True),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['feed_instance_id'], ['feed_instances.id'], name=op.f('fk_feed_instance_entries_feed_instance_id_feed_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_feed_instance_entries_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feed_instance_id', 'story_id', name=op.f('pk_feed_instance_entries'))
    )
    op.create_index('ix_feed_entries_order', 'feed_instance_entries', ['feed_instance_id', 'published_at'], unique=False)
    op.create_index('ix_feed_entries_rank', 'feed_instance_entries', ['feed_instance_id', 'rank_score'], unique=False)
    op.create_table('feed_instance_source_types',
    sa.Column('feed_instance_id', sa.Integer(), nullable=False),
    sa.Column('source_type_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.CheckConstraint("mode IN ('include', 'exclude')", name=op.f('ck_feed_instance_source_types_feed_source_type_mode_known')),
    sa.ForeignKeyConstraint(['feed_instance_id'], ['feed_instances.id'], name=op.f('fk_feed_instance_source_types_feed_instance_id_feed_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_type_id'], ['source_types.id'], name=op.f('fk_feed_instance_source_types_source_type_id_source_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feed_instance_id', 'source_type_id', name=op.f('pk_feed_instance_source_types'))
    )
    op.create_table('feed_instance_tags',
    sa.Column('feed_instance_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.CheckConstraint("NOT (is_required AND mode = 'exclude')", name=op.f('ck_feed_instance_tags_excluded_tag_cannot_be_required')),
    sa.CheckConstraint("mode IN ('include', 'exclude')", name=op.f('ck_feed_instance_tags_feed_tag_mode_known')),
    sa.ForeignKeyConstraint(['feed_instance_id'], ['feed_instances.id'], name=op.f('fk_feed_instance_tags_feed_instance_id_feed_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_feed_instance_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feed_instance_id', 'tag_id', name=op.f('pk_feed_instance_tags'))
    )
    op.create_index('ix_feed_instance_tags_mode', 'feed_instance_tags', ['feed_instance_id', 'mode'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_error', sa.Text(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], name=op.f('fk_notifications_acknowledged_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_trigger'), 'notifications', ['trigger'], unique=False)
    op.create_index('ix_notifications_undelivered', 'notifications', ['delivered_at', 'created_at'], unique=False)
    op.create_table('saved_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_saved_views_owner_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_views')),
    sa.UniqueConstraint('slug', name=op.f('uq_saved_views_slug'))
    )
    op.create_index(op.f('ix_saved_views_owner_user_id'), 'saved_views', ['owner_user_id'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_settings_updated_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('feed_url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('source_type_id', sa.Integer(), nullable=True),
    sa.Column('context', sa.String(length=40), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('fetch_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('request_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_items_per_fetch', sa.Integer(), nullable=False),
    sa.Column('http_etag', sa.String(length=400), nullable=True),
    sa.Column('http_last_modified', sa.String(length=200), nullable=True),
    sa.Column('last_fetch_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_fetch_succeeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_fetch_failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_http_status', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_response_ms', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('disabled_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("context IS NULL OR context IN ('established_publication', 'government', 'local', 'industry', 'research', 'primary', 'secondary', 'opinion', 'analysis')", name=op.f('ck_sources_source_context_known')),
    sa.CheckConstraint('consecutive_failures >= 0', name=op.f('ck_sources_failures_non_negative')),
    sa.CheckConstraint('fetch_interval_seconds >= 60', name=op.f('ck_sources_fetch_interval_polite')),
    sa.ForeignKeyConstraint(['source_type_id'], ['source_types.id'], name=op.f('fk_sources_source_type_id_source_types'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('slug', name=op.f('uq_sources_slug'))
    )
    op.create_index('ix_sources_due', 'sources', ['is_active', 'last_fetch_attempted_at'], unique=False)
    op.create_index(op.f('ix_sources_source_type_id'), 'sources', ['source_type_id'], unique=False)
    op.create_table('story_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('is_conflicting', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_value_id', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resolved_value_id'], ['story_claim_values.id'], name='fk_story_claims_resolved_value_id_story_claim_values', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_claims_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_claims'))
    )
    op.create_index(op.f('ix_story_claims_story_id'), 'story_claims', ['story_id'], unique=False)
    op.create_table('story_tags',
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_tags_story_id_stories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_story_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('story_id', 'tag_id', name=op.f('pk_story_tags'))
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('original_guid', sa.String(length=500), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('original_canonical_url', sa.Text(), nullable=True),
    sa.Column('original_headline', sa.Text(), nullable=False),
    sa.Column('original_description', sa.Text(), nullable=True),
    sa.Column('original_author', sa.String(length=300), nullable=True),
    sa.Column('original_image_url', sa.Text(), nullable=True),
    sa.Column('original_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('original_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalized_url', sa.Text(), nullable=True),
    sa.Column('normalized_title', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('story_match_confidence', sa.Float(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('ai_processing_disabled', sa.Boolean(), nullable=False),
    sa.Column('has_manual_override', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id <> duplicate_of_id', name=op.f('ck_articles_article_not_its_own_duplicate')),
    sa.CheckConstraint('importance_score IS NULL OR (importance_score >= 0 AND importance_score <= 100)', name=op.f('ck_articles_importance_in_range')),
    sa.CheckConstraint('story_match_confidence IS NULL OR (story_match_confidence >= 0 AND story_match_confidence <= 1)', name=op.f('ck_articles_confidence_in_unit_range')),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['articles.id'], name=op.f('fk_articles_duplicate_of_id_articles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_articles_source_id_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_articles_story_id_stories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles')),
    sa.UniqueConstraint('source_id', 'normalized_url', name='source_normalized_url'),
    sa.UniqueConstraint('source_id', 'original_guid', name='source_guid')
    )
    op.create_index(op.f('ix_articles_content_hash'), 'articles', ['content_hash'], unique=False)
    op.create_index(op.f('ix_articles_duplicate_of_id'), 'articles', ['duplicate_of_id'], unique=False)
    op.create_index(op.f('ix_articles_normalized_title'), 'articles', ['normalized_title'], unique=False)
    op.create_index(op.f('ix_articles_normalized_url'), 'articles', ['normalized_url'], unique=False)
    op.create_index('ix_articles_published', 'articles', ['original_published_at'], unique=False)
    op.create_index(op.f('ix_articles_source_id'), 'articles', ['source_id'], unique=False)
    op.create_index(op.f('ix_articles_story_id'), 'articles', ['story_id'], unique=False)
    op.create_index('ix_articles_story_published', 'articles', ['story_id', 'original_published_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['change_history.id'], name=op.f('fk_audit_logs_change_id_change_history'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('feed_instance_sources',
    sa.Column('feed_instance_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.CheckConstraint("mode IN ('include', 'exclude')", name=op.f('ck_feed_instance_sources_feed_source_mode_known')),
    sa.ForeignKeyConstraint(['feed_instance_id'], ['feed_instances.id'], name=op.f('fk_feed_instance_sources_feed_instance_id_feed_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_feed_instance_sources_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feed_instance_id', 'source_id', name=op.f('pk_feed_instance_sources'))
    )
    op.create_table('source_fetch_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('response_ms', sa.Integer(), nullable=True),
    sa.Column('items_returned', sa.Integer(), nullable=True),
    sa.Column('items_new', sa.Integer(), nullable=True),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('not_modified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_fetch_logs_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_fetch_logs'))
    )
    op.create_index('ix_source_fetch_logs_recent', 'source_fetch_logs', ['source_id', 'attempted_at'], unique=False)
    op.create_index(op.f('ix_source_fetch_logs_source_id'), 'source_fetch_logs', ['source_id'], unique=False)
    op.create_table('source_tags',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_tags_source_id_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_source_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', 'tag_id', name=op.f('pk_source_tags'))
    )
    op.create_table('ai_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=60), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('edited_content', sa.Text(), nullable=True),
    sa.Column('edited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(target_type = 'article' AND article_id IS NOT NULL AND story_id IS NULL) OR (target_type = 'story' AND story_id IS NOT NULL AND article_id IS NULL)", name=op.f('ck_ai_results_ai_target_matches_id')),
    sa.CheckConstraint("operation IN ('generate_headline', 'generate_summary', 'classify_article', 'extract_entities', 'create_embeddings', 'cluster_stories', 'synthesize_story', 'identify_conflicts')", name=op.f('ck_ai_results_ai_operation_known')),
    sa.CheckConstraint("review_state IN ('auto_accepted', 'pending_review', 'approved', 'rejected', 'superseded')", name=op.f('ck_ai_results_ai_review_state_known')),
    sa.CheckConstraint("target_type IN ('article', 'story')", name=op.f('ck_ai_results_ai_target_known')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_ai_results_ai_confidence_range')),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_ai_results_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edited_by_user_id'], ['users.id'], name=op.f('fk_ai_results_edited_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_ai_results_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_results'))
    )
    op.create_index(op.f('ix_ai_results_article_id'), 'ai_results', ['article_id'], unique=False)
    op.create_index('ix_ai_results_history', 'ai_results', ['target_type', 'operation', 'generated_at'], unique=False)
    op.create_index(op.f('ix_ai_results_input_fingerprint'), 'ai_results', ['input_fingerprint'], unique=False)
    op.create_index(op.f('ix_ai_results_story_id'), 'ai_results', ['story_id'], unique=False)
    op.create_index('uq_ai_results_current_article', 'ai_results', ['article_id', 'operation'], unique=True, postgresql_where=sa.text('is_current IS true AND article_id IS NOT NULL'))
    op.create_index('uq_ai_results_current_story', 'ai_results', ['story_id', 'operation'], unique=True, postgresql_where=sa.text('is_current IS true AND story_id IS NOT NULL'))
    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('operation', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('feed_instance_id', sa.Integer(), nullable=True),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("operation IN ('generate_headline', 'generate_summary', 'classify_article', 'extract_entities', 'create_embeddings', 'cluster_stories', 'synthesize_story', 'identify_conflicts')", name=op.f('ck_ai_usage_usage_operation_known')),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_ai_usage_article_id_articles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['feed_instance_id'], ['feed_instances.id'], name=op.f('fk_ai_usage_feed_instance_id_feed_instances'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_ai_usage_source_id_sources'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_ai_usage_story_id_stories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_usage'))
    )
    op.create_index(op.f('ix_ai_usage_article_id'), 'ai_usage', ['article_id'], unique=False)
    op.create_index(op.f('ix_ai_usage_feed_instance_id'), 'ai_usage', ['feed_instance_id'], unique=False)
    op.create_index(op.f('ix_ai_usage_occurred_at'), 'ai_usage', ['occurred_at'], unique=False)
    op.create_index('ix_ai_usage_rollup', 'ai_usage', ['occurred_at', 'provider', 'model'], unique=False)
    op.create_index(op.f('ix_ai_usage_source_id'), 'ai_usage', ['source_id'], unique=False)
    op.create_index(op.f('ix_ai_usage_story_id'), 'ai_usage', ['story_id'], unique=False)
    op.create_table('article_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=300), nullable=False),
    sa.Column('normalized_value', sa.String(length=300), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.CheckConstraint("kind IN ('person', 'organization', 'location', 'event', 'date', 'other')", name=op.f('ck_article_entities_entity_kind_known')),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_entities_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article_entities')),
    sa.UniqueConstraint('article_id', 'kind', 'normalized_value', name='entity_once')
    )
    op.create_index(op.f('ix_article_entities_article_id'), 'article_entities', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_entities_normalized_value'), 'article_entities', ['normalized_value'], unique=False)
    op.create_table('article_tags',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_article_tags_article_tag_confidence_range')),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_article_tags_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_article_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'tag_id', name=op.f('pk_article_tags'))
    )
    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('queue_job_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stage IN ('fetch', 'normalize', 'deduplicate', 'extract_metadata', 'tag', 'cluster', 'generate_ai', 'score', 'publish')", name=op.f('ck_processing_jobs_job_stage_known')),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled')", name=op.f('ck_processing_jobs_job_status_known')),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_processing_jobs_job_attempts_non_negative')),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_processing_jobs_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_processing_jobs_source_id_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_processing_jobs_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_jobs'))
    )
    op.create_index(op.f('ix_processing_jobs_article_id'), 'processing_jobs', ['article_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_queue_job_id'), 'processing_jobs', ['queue_job_id'], unique=False)
    op.create_index('ix_processing_jobs_runnable', 'processing_jobs', ['status', 'run_after'], unique=False)
    op.create_index(op.f('ix_processing_jobs_source_id'), 'processing_jobs', ['source_id'], unique=False)
    op.create_index('ix_processing_jobs_stage_status', 'processing_jobs', ['stage', 'status'], unique=False)
    op.create_index(op.f('ix_processing_jobs_story_id'), 'processing_jobs', ['story_id'], unique=False)
    op.create_table('scoring_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('score_kind', sa.String(length=20), nullable=False),
    sa.Column('factor', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('story_id IS NOT NULL OR article_id IS NOT NULL', name=op.f('ck_scoring_factors_scoring_factor_has_target')),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_scoring_factors_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_scoring_factors_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scoring_factors'))
    )
    op.create_index(op.f('ix_scoring_factors_article_id'), 'scoring_factors', ['article_id'], unique=False)
    op.create_index('ix_scoring_factors_lookup', 'scoring_factors', ['story_id', 'score_kind', 'computed_at'], unique=False)
    op.create_index(op.f('ix_scoring_factors_story_id'), 'scoring_factors', ['story_id'], unique=False)
    op.create_table('story_articles',
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('is_first_report', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_story_articles_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], name=op.f('fk_story_articles_assigned_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_articles_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('story_id', 'article_id', name=op.f('pk_story_articles'))
    )
    op.create_table('story_claim_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_story_claim_values_article_id_articles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['claim_id'], ['story_claims.id'], name=op.f('fk_story_claim_values_claim_id_story_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_story_claim_values_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_claim_values'))
    )
    op.create_index(op.f('ix_story_claim_values_article_id'), 'story_claim_values', ['article_id'], unique=False)
    op.create_index(op.f('ix_story_claim_values_claim_id'), 'story_claim_values', ['claim_id'], unique=False)
    op.create_index(op.f('ix_story_claim_values_source_id'), 'story_claim_values', ['source_id'], unique=False)
    op.create_table('story_timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_article_id', sa.Integer(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_article_id IS NOT NULL OR is_manual', name=op.f('ck_story_timeline_events_timeline_entry_is_sourced')),
    sa.ForeignKeyConstraint(['source_article_id'], ['articles.id'], name=op.f('fk_story_timeline_events_source_article_id_articles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_timeline_events_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_timeline_events'))
    )
    op.create_index(op.f('ix_story_timeline_events_story_id'), 'story_timeline_events', ['story_id'], unique=False)
    op.create_index('ix_story_timeline_order', 'story_timeline_events', ['story_id', 'occurred_at'], unique=False)
    op.create_table('ai_result_inputs',
    sa.Column('ai_result_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ai_result_id'], ['ai_results.id'], name=op.f('fk_ai_result_inputs_ai_result_id_ai_results'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_ai_result_inputs_article_id_articles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ai_result_id', 'article_id', name=op.f('pk_ai_result_inputs'))
    )
    op.create_table('review_queue_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=60), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('ai_result_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('auto_accepted', 'pending_review', 'approved', 'rejected', 'superseded')", name=op.f('ck_review_queue_items_review_item_state_known')),
    sa.CheckConstraint('article_id IS NOT NULL OR story_id IS NOT NULL OR ai_result_id IS NOT NULL', name=op.f('ck_review_queue_items_review_item_has_target')),
    sa.ForeignKeyConstraint(['ai_result_id'], ['ai_results.id'], name=op.f('fk_review_queue_items_ai_result_id_ai_results'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_review_queue_items_article_id_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], name=op.f('fk_review_queue_items_resolved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_review_queue_items_story_id_stories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_queue_items'))
    )
    op.create_index(op.f('ix_review_queue_items_article_id'), 'review_queue_items', ['article_id'], unique=False)
    op.create_index(op.f('ix_review_queue_items_reason'), 'review_queue_items', ['reason'], unique=False)
    op.create_index(op.f('ix_review_queue_items_story_id'), 'review_queue_items', ['story_id'], unique=False)
    op.create_index('ix_review_queue_open', 'review_queue_items', ['state', 'created_at'], unique=False)
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # Layer 1 protection — Non-Negotiable #1, enforced by the database.
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE OR REPLACE FUNCTION reject_original_data_mutation()
        RETURNS trigger AS $$
        BEGIN
            IF NEW.original_guid IS DISTINCT FROM OLD.original_guid THEN
                RAISE EXCEPTION 'articles.original_guid is original source data and cannot be modified (Non-Negotiable #1)'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            IF NEW.original_url IS DISTINCT FROM OLD.original_url THEN
                RAISE EXCEPTION 'articles.original_url is original source data and cannot be modified (Non-Negotiable #1)'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            IF NEW.original_canonical_url IS DISTINCT FROM OLD.original_canonical_url THEN
                RAISE EXCEPTION 'articles.original_canonical_url is original source data and cannot be modified (Non-Negotiable #1)'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            IF NEW.original_headline IS DISTINCT FROM OLD.original_headline THEN
                RAISE EXCEPTION 'articles.original_headline is original source data and cannot be modified (Non-Negotiable #1)'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            IF NEW.original_description IS DISTINCT FROM OLD.original_description THEN
                RAISE EXCEPTION 'articles.original_description is original source data and cannot be modified (Non-Negotiable #1)'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            IF NEW.original_author IS DISTINCT FROM OLD.original_author THEN
                RAISE EXCEPTION 'articles.original_author is original source data and cannot be modified (Non-Negotiable #1)'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            IF NEW.original_image_url IS DISTINCT FROM OLD.original_image_url THEN
                RAISE EXCEPTION 'articles.original_image_url is original source data and cannot be modified (Non-Negotiable #1)'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            IF NEW.original_published_at IS DISTINCT FROM OLD.original_published_at THEN
                RAISE EXCEPTION 'articles.original_published_at is original source data and cannot be modified (Non-Negotiable #1)'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            IF NEW.original_payload IS DISTINCT FROM OLD.original_payload THEN
                RAISE EXCEPTION 'articles.original_payload is original source data and cannot be modified (Non-Negotiable #1)'
                    USING ERRCODE = 'restrict_violation';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER articles_original_data_is_immutable
        BEFORE UPDATE ON articles
        FOR EACH ROW EXECUTE FUNCTION reject_original_data_mutation();
        """
    )

    # ------------------------------------------------------------------
    # updated_at maintenance — a row cannot change without the clock moving.
    # ------------------------------------------------------------------
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at()
        RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = clock_timestamp();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table in TIMESTAMPED_TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_set_updated_at BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
        )


def downgrade() -> None:
    for table in TIMESTAMPED_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_set_updated_at ON {table};")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at();")
    op.execute("DROP TRIGGER IF EXISTS articles_original_data_is_immutable ON articles;")
    op.execute("DROP FUNCTION IF EXISTS reject_original_data_mutation();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_queue_open', table_name='review_queue_items')
    op.drop_index(op.f('ix_review_queue_items_story_id'), table_name='review_queue_items')
    op.drop_index(op.f('ix_review_queue_items_reason'), table_name='review_queue_items')
    op.drop_index(op.f('ix_review_queue_items_article_id'), table_name='review_queue_items')
    op.drop_table('review_queue_items')
    op.drop_table('ai_result_inputs')
    op.drop_index('ix_story_timeline_order', table_name='story_timeline_events')
    op.drop_index(op.f('ix_story_timeline_events_story_id'), table_name='story_timeline_events')
    op.drop_table('story_timeline_events')
    op.drop_index(op.f('ix_story_claim_values_source_id'), table_name='story_claim_values')
    op.drop_index(op.f('ix_story_claim_values_claim_id'), table_name='story_claim_values')
    op.drop_index(op.f('ix_story_claim_values_article_id'), table_name='story_claim_values')
    op.drop_table('story_claim_values')
    op.drop_table('story_articles')
    op.drop_index(op.f('ix_scoring_factors_story_id'), table_name='scoring_factors')
    op.drop_index('ix_scoring_factors_lookup', table_name='scoring_factors')
    op.drop_index(op.f('ix_scoring_factors_article_id'), table_name='scoring_factors')
    op.drop_table('scoring_factors')
    op.drop_index(op.f('ix_processing_jobs_story_id'), table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_stage_status', table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_source_id'), table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_runnable', table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_queue_job_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_article_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_table('article_tags')
    op.drop_index(op.f('ix_article_entities_normalized_value'), table_name='article_entities')
    op.drop_index(op.f('ix_article_entities_article_id'), table_name='article_entities')
    op.drop_table('article_entities')
    op.drop_index(op.f('ix_ai_usage_story_id'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_source_id'), table_name='ai_usage')
    op.drop_index('ix_ai_usage_rollup', table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_occurred_at'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_feed_instance_id'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_article_id'), table_name='ai_usage')
    op.drop_table('ai_usage')
    op.drop_index('uq_ai_results_current_story', table_name='ai_results', postgresql_where=sa.text('is_current IS true AND story_id IS NOT NULL'))
    op.drop_index('uq_ai_results_current_article', table_name='ai_results', postgresql_where=sa.text('is_current IS true AND article_id IS NOT NULL'))
    op.drop_index(op.f('ix_ai_results_story_id'), table_name='ai_results')
    op.drop_index(op.f('ix_ai_results_input_fingerprint'), table_name='ai_results')
    op.drop_index('ix_ai_results_history', table_name='ai_results')
    op.drop_index(op.f('ix_ai_results_article_id'), table_name='ai_results')
    op.drop_table('ai_results')
    op.drop_table('source_tags')
    op.drop_index(op.f('ix_source_fetch_logs_source_id'), table_name='source_fetch_logs')
    op.drop_index('ix_source_fetch_logs_recent', table_name='source_fetch_logs')
    op.drop_table('source_fetch_logs')
    op.drop_table('feed_instance_sources')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_articles_story_published', table_name='articles')
    op.drop_index(op.f('ix_articles_story_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_source_id'), table_name='articles')
    op.drop_index('ix_articles_published', table_name='articles')
    op.drop_index(op.f('ix_articles_normalized_url'), table_name='articles')
    op.drop_index(op.f('ix_articles_normalized_title'), table_name='articles')
    op.drop_index(op.f('ix_articles_duplicate_of_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_content_hash'), table_name='articles')
    op.drop_table('articles')
    op.drop_table('story_tags')
    op.drop_index(op.f('ix_story_claims_story_id'), table_name='story_claims')
    op.drop_table('story_claims')
    op.drop_index(op.f('ix_sources_source_type_id'), table_name='sources')
    op.drop_index('ix_sources_due', table_name='sources')
    op.drop_table('sources')
    op.drop_table('settings')
    op.drop_index(op.f('ix_saved_views_owner_user_id'), table_name='saved_views')
    op.drop_table('saved_views')
    op.drop_index('ix_notifications_undelivered', table_name='notifications')
    op.drop_index(op.f('ix_notifications_trigger'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_feed_instance_tags_mode', table_name='feed_instance_tags')
    op.drop_table('feed_instance_tags')
    op.drop_table('feed_instance_source_types')
    op.drop_index('ix_feed_entries_rank', table_name='feed_instance_entries')
    op.drop_index('ix_feed_entries_order', table_name='feed_instance_entries')
    op.drop_table('feed_instance_entries')
    op.drop_index(op.f('ix_change_history_occurred_at'), table_name='change_history')
    op.drop_index('ix_change_history_entity', table_name='change_history')
    op.drop_table('change_history')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_parent_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index('ix_system_logs_recent', table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_logged_at'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index('ix_stories_trending', table_name='stories')
    op.drop_index('ix_stories_state', table_name='stories')
    op.drop_table('stories')
    op.drop_table('source_types')
    op.drop_table('reader_preferences')
    op.drop_table('feed_instances')
    # ### end Alembic commands ###
